### ISSUE TITLE
Magento download without login doesn't work anymore

### ISSUE THREAD

**Issue by mblarsen** [silpion/ansible-magento#1]
You are now required to log in to be able to download.

Perhaps in addition to the `copy` function you should be able to provide a downloaded archive.

**Comment by cascaya** [comment]
You  can download the archive manual to `magento_download_tmp_dir` and configure `magento_download` and `magento_copy` to `'no'`. This will upload the archive to the remote node and extract it there without even trying a download.

Hope this helps,

Anja
